# Generated by Django 3.0.6 on 2020-05-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='test deesctip'),
            preserve_default=False,
        ),
    ]
